version: "3.8" # Keep this line if you want to specify the version
services:
  db:
    image: postgres:17-alpine
    container_name: postgres_three
    environment:
      POSTGRES_PASSWORD: rsh
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432" # Add this line to expose the PostgreSQL port
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=rsh
      - DB_NAME=postgres
    restart: on-failure

volumes:
  postgres_data:
